blank_issues_enabled: false
contact_links:
  - name: Questions 问题讨论
    url: https://github.com/orgs/fixit-theme/discussions
    about: Please ask questions in Discussion. 请在讨论中提问。

  - name: Theme Documentation 主题文档
    url: https://github.com/fixit-theme/hugo-shortcode-plugins-live2d#readme
    about: Please read the documentation carefully. 请先仔细阅读主题文档。
